import { useState } from 'react';
import { Link } from 'react-router-dom';
import { usePortal } from './PortalContext';
import { usePortalRoute } from './PortalLayout';
import { dateLabel, roleNames, specialties, today, uid } from './data';
import { Badge, Empty, Field, Heading, Modal, Panel, Progress, Stats, Table, TextArea, exportCSV, formValues } from './ui';

export function Users() {
  const { data, update, remove, notify } = usePortal();
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('');
  const [editing, setEditing] = useState(null);
  const [deleting, setDeleting] = useState(null);
  const [error, setError] = useState('');
  const rows = data.users.filter(u => `${u.nombre} ${u.correo}`.toLowerCase().includes(search.toLowerCase()) && (!filter || u.rol === filter));
  function save(e) {
    e.preventDefault(); const values = formValues(e);
    if (data.users.some(u => u.id !== editing.id && u.correo.toLowerCase() === values.correo.trim().toLowerCase())) { setError('Ya existe un usuario con ese correo.'); return; }
    if (editing.id === 'ana' && values.rol !== 'admin') { setError('Mantén el rol de la coordinadora de demostración para conservar el acceso.'); return; }
    if (values.rol !== 'estudiante' && data.projects.some(p => p.owner === editing.id)) { setError('Este usuario tiene proyectos asociados; conserva su rol de Emprendedor.'); return; }
    update('users', { ...values, correo: values.correo.trim(), id: editing.id || uid() }); setEditing(null); setError(''); notify('Usuario guardado en la demostración. No se creó ni modificó una cuenta real.');
  }
  return <><Heading eyebrow="COORDINACIÓN / USUARIOS" title="Usuarios registrados" description="Las personas que forman parte de nuestra comunidad." action={<button className="button" onClick={() => { setEditing({}); setError(''); }}>+ Nuevo usuario</button>} /><Panel><div className="filters"><Field label="Buscar usuario" value={search} onChange={e => setSearch(e.target.value)} placeholder="Nombre o correo…" /><Field label="Rol" value={filter} onChange={e => setFilter(e.target.value)}><option value="">Todos los roles</option>{Object.entries(roleNames).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</Field></div><Table headings={['Nombre', 'Correo', 'Rol', 'Especialidad', 'Acciones']} empty={!rows.length}>{rows.map(u => <tr key={u.id}><td><strong>{u.nombre}</strong></td><td>{u.correo}</td><td><Badge>{roleNames[u.rol]}</Badge></td><td>{u.especialidad || '—'}</td><td><div className="row"><button className="text-button" onClick={() => { setEditing(u); setError(''); }}>Editar</button><button className="text-button danger" disabled={['ana', 'diego', 'karla'].includes(u.id)} onClick={() => setDeleting(u)}>Eliminar</button></div></td></tr>)}</Table><p className="helper">Las tres cuentas de vista previa se conservan para poder recorrer todos los portales.</p></Panel>
    {editing && <Modal title={editing.id ? 'Editar usuario' : 'Nuevo usuario'} onClose={() => setEditing(null)}><form className="form-stack" onSubmit={save}><Field label="Nombre completo" name="nombre" required maxLength={120} defaultValue={editing.nombre} /><Field label="Correo" name="correo" type="email" required defaultValue={editing.correo} /><Field label="Rol" name="rol" defaultValue={editing.rol || 'estudiante'}>{Object.entries(roleNames).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</Field><Field label="Especialidad" name="especialidad" defaultValue={editing.especialidad || ''}><option value="">Sin especialidad</option>{specialties.map(s => <option key={s}>{s}</option>)}</Field>{error && <p className="error" role="alert">{error}</p>}<button className="button">Guardar usuario</button></form></Modal>}
    {deleting && <Modal title="Eliminar usuario de ejemplo" onClose={() => setDeleting(null)}>{data.projects.some(p => p.owner === deleting.id) || data.registrations.some(r => r.user === deleting.id) || data.payments.some(p => p.user === deleting.id) ? <><p>Este usuario tiene proyectos, inscripciones o pagos asociados. Conserva su ficha para mantener el historial.</p><button className="button secondary" onClick={() => setDeleting(null)}>Volver</button></> : <><p>¿Eliminar a {deleting.nombre} de esta demostración?</p><div className="form-actions"><button className="button secondary" onClick={() => setDeleting(null)}>Cancelar</button><button className="button" onClick={() => { remove('users', deleting.id); setDeleting(null); }}>Eliminar</button></div></>}</Modal>}
  </>;
}

export function Roles() {
  const { data, update, notify } = usePortal();
  const [editing, setEditing] = useState(null);
  return <><Heading eyebrow="COORDINACIÓN / ROLES" title="Roles y permisos" description="Un espacio para cada persona, con acceso a lo que necesita." action={<button className="button" onClick={() => setEditing({})}>+ Nuevo rol</button>} /><Panel><Table headings={['Rol', 'Descripción', 'Permisos generales', 'Acciones']}>{data.roles.map(r => <tr key={r.id}><td><strong>{r.nombre}</strong></td><td>{r.descripcion}</td><td><Badge>{r.permisos}</Badge></td><td><button className="text-button" onClick={() => setEditing(r)}>Editar</button></td></tr>)}</Table><p className="info-box">Los roles adicionales son propuestas de catálogo. Solo los tres roles existentes tienen acceso definido; editar esta vista no cambia los permisos reales.</p></Panel>{editing && <Modal title={editing.id ? 'Editar descripción del rol' : 'Proponer nuevo rol'} onClose={() => setEditing(null)}><form className="form-stack" onSubmit={e => { e.preventDefault(); update('roles', { ...formValues(e), id: editing.id || uid() }); setEditing(null); notify('Propuesta de rol guardada en la demostración.'); }}><Field label="Nombre" name="nombre" required maxLength={80} defaultValue={editing.nombre} /><TextArea label="Descripción" name="descripcion" required maxLength={500} defaultValue={editing.descripcion} /><Field label="Alcance propuesto" name="permisos" required maxLength={100} defaultValue={editing.permisos} /><button className="button">Guardar propuesta</button></form></Modal>}</>;
}

export function Reports({ initialTab = 'proyectos' }) {
  const { data } = usePortal();
  const { base } = usePortalRoute();
  const [tab, setTab] = useState(initialTab);
  const [specialty, setSpecialty] = useState('');
  const [status, setStatus] = useState('');
  const projects = data.projects.filter(p => (!specialty || p.especialidad === specialty) && (!status || p.estatus === status));
  const users = data.users.filter(u => u.rol === 'estudiante' && (!specialty || u.especialidad === specialty));
  const milestones = data.milestones.filter(m => projects.some(p => p.id === m.project));
  const headings = tab === 'emprendedores' ? ['Nombre', 'Correo', 'Especialidad', 'Proyectos'] : tab === 'avances' ? ['Proyecto', 'Hito', 'Notas', 'Fecha'] : ['Proyecto', 'Especialidad', 'Inicio', 'Progreso', 'Estatus'];
  const rows = tab === 'emprendedores' ? users.map(u => [u.nombre, u.correo, u.especialidad, data.projects.filter(p => p.owner === u.id).length]) : tab === 'avances' ? milestones.map(m => [data.projects.find(p => p.id === m.project)?.nombre, m.hito, m.notas, dateLabel(m.fecha)]) : projects.map(p => [p.nombre, p.especialidad, dateLabel(p.fecha), `${p.progreso}%`, p.estatus]);
  return <><Heading eyebrow="COORDINACIÓN / REPORTES" title="Información para acompañar mejor" description="Consulta, filtra y exporta el seguimiento de la incubadora." action={tab !== 'estadisticas' && <button className="button secondary" onClick={() => exportCSV(`reporte-${tab}-demo.csv`, headings, rows)}>Exportar CSV para Excel</button>} /><div className="tabs">{[['emprendedores', 'Emprendedores'], ['proyectos', 'Proyectos'], ['avances', 'Avances'], ['estadisticas', 'Estadísticas']].map(([id, name]) => <button key={id} aria-pressed={tab === id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{name}</button>)}</div><div className="filters"><Field label="Especialidad" value={specialty} onChange={e => setSpecialty(e.target.value)}><option value="">Todas las especialidades</option>{specialties.map(s => <option key={s}>{s}</option>)}</Field>{tab !== 'emprendedores' && <Field label="Estatus de proyecto" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos los estatus</option>{['Pendiente', 'En proceso', 'Completado'].map(s => <option key={s}>{s}</option>)}</Field>}</div>
    {tab === 'estadisticas' ? <><Stats items={[[ 'Proyectos', projects.length], ['Emprendedores', users.length], ['Eventos activos', data.events.filter(e => e.estatus === 'Activo').length], ['Progreso promedio', `${Math.round(projects.reduce((sum, p) => sum + p.progreso, 0) / (projects.length || 1))}%`]]} /><div className="two-columns"><Panel title="Proyectos por especialidad">{specialties.map(s => { const count = projects.filter(p => p.especialidad === s).length; return <div className="chart-row" key={s}><div className="row between"><span>{s}</span><strong>{count}</strong></div><meter min="0" max={Math.max(projects.length, 1)} value={count} aria-label={`${s}: ${count} proyectos`} /></div>; })}</Panel><Panel title="Estatus de proyectos">{['En proceso', 'Completado', 'Pendiente'].map(s => <div className="status-row" key={s}><Badge>{s}</Badge><strong>{projects.filter(p => p.estatus === s).length}</strong></div>)}<Link className="text-link" to={`${base}/seguimiento`}>Ir al seguimiento →</Link></Panel></div></> : <Panel title={`Reporte de ${tab}`}><Table headings={headings} empty={!rows.length}>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{j === 0 ? <strong>{cell}</strong> : cell}</td>)}</tr>)}</Table></Panel>}
  </>;
}

export function Application({ admin = false }) {
  const { data, update, setData, notify } = usePortal();
  const { userId } = usePortalRoute();
  const existing = data.requests.find(r => r.user === userId);
  const [error, setError] = useState('');
  const [detail, setDetail] = useState(null);
  function submit(e) {
    e.preventDefault(); if (existing && existing.estatus !== 'Rechazada') return;
    const values = formValues(e);
    if (!values.nombre.trim() || !values.descripcion.trim()) { setError('Completa el nombre y la descripción de tu propuesta.'); return; }
    update('requests', { ...values, id: existing?.id || uid(), user: userId, fecha: today(), estatus: 'En revisión' }); notify('Solicitud enviada en esta demostración. Puedes revisar su estado aquí.'); setError('');
  }
  if (admin) return <><Heading title="Solicitudes de ingreso" description="Conoce las ideas de quienes quieren sumarse a la incubadora." /><Panel><Table headings={['Solicitante', 'Proyecto', 'Especialidad', 'Fecha', 'Estado', 'Acción']} empty={!data.requests.length}>{data.requests.map(r => <tr key={r.id}><td>{data.users.find(u => u.id === r.user)?.nombre}</td><td>{r.nombre}</td><td>{r.especialidad}</td><td>{dateLabel(r.fecha)}</td><td><Badge>{r.estatus}</Badge></td><td><button className="text-button" onClick={() => setDetail(r)}>Revisar</button></td></tr>)}</Table></Panel>{detail && <Modal title={detail.nombre} onClose={() => setDetail(null)}><p>{detail.descripcion}</p><p>Teléfono: {detail.telefono}</p><p className="info-box">La decisión se registra únicamente en la demostración. El cambio de rol de la cuenta requiere conectarse al servidor.</p>{detail.estatus === 'En revisión' && <div className="form-actions"><button className="button secondary" onClick={() => { update('requests', { ...detail, estatus: 'Rechazada' }); setDetail(null); }}>Rechazar propuesta</button><button className="button" onClick={() => { update('requests', { ...detail, estatus: 'Aprobada' }); setDetail(null); notify('Solicitud aprobada en la demostración; no se modificaron permisos reales.'); }}>Aprobar propuesta</button></div>}</Modal>}</>;
  return <><Heading eyebrow="EXTERNO / SOLICITUD DE INGRESO" title="Tu idea puede ser el siguiente gran proyecto" description="Cuéntanos qué quieres construir. La coordinación revisará tu propuesta." /><div className="two-columns form-columns"><Panel title="Nueva solicitud">{existing && existing.estatus !== 'Rechazada' ? <div className="empty-state"><h3>Ya recibimos tu propuesta de demostración</h3><p>{existing.nombre}</p><p>Consulta el estado de tu solicitud en este panel.</p></div> : <form className="form-stack" onSubmit={submit}><Field label="Nombre de tu proyecto o idea" name="nombre" required maxLength={160} defaultValue={existing?.nombre} placeholder="Ej. Ruta Verde Logística" /><TextArea label="Describe tu proyecto" name="descripcion" required maxLength={3000} defaultValue={existing?.descripcion} placeholder="¿Qué problema resuelve y en qué etapa se encuentra?" /><Field label="Especialidad / carrera" name="especialidad" required defaultValue={existing?.especialidad}>{specialties.map(s => <option key={s}>{s}</option>)}</Field><Field label="Teléfono de contacto" name="telefono" type="tel" pattern="[0-9+ ()-]{10,20}" required defaultValue={existing?.telefono} placeholder="844 000 0000" />{error && <p className="error" role="alert">{error}</p>}<button className="button">Enviar solicitud</button></form>}</Panel><div><Panel title="Estado de mi solicitud">{existing ? <><Badge>{existing.estatus}</Badge><p>Enviada el {dateLabel(existing.fecha)}.</p><p className="muted">{existing.estatus === 'En revisión' ? 'La coordinación revisará tu proyecto para continuar con el proceso de ingreso.' : existing.estatus === 'Aprobada' ? 'Tu propuesta fue aprobada en la demostración. La activación del rol se realizará cuando se conecte este proceso al servidor.' : 'Tu propuesta requiere ajustes. Puedes actualizarla y enviarla de nuevo.'}</p></> : <><Badge>Sin solicitud</Badge><p className="muted">Completa el formulario para dar el primer paso.</p></>}</Panel><Panel title="¿Cómo funciona?"><ol className="steps-list"><li>Comparte tu idea.</li><li>La coordinación revisa tu propuesta.</li><li>Recibe orientación para comenzar.</li></ol></Panel></div></div></>;
}

export function Tutoring({ initialTab }) {
  const { data, update, remove, setData, notify } = usePortal();
  const { role, userId } = usePortalRoute();
  const admin = role === 'admin';
  const [tab, setTab] = useState(initialTab || (admin ? 'agenda' : 'agendar'));
  const [selected, setSelected] = useState('');
  const [modal, setModal] = useState(false);
  const [error, setError] = useState('');
  const appointments = data.appointments.filter(a => admin || a.user === userId);
  const available = data.slots.filter(s => s.fecha >= today() && !data.appointments.some(a => a.slot === s.id && a.estatus === 'Confirmada'));
  function createSlot(e) {
    e.preventDefault(); const values = formValues(e);
    if (values.fin <= values.inicio || data.slots.some(s => s.fecha === values.fecha && s.inicio < values.fin && s.fin > values.inicio)) { setError('Elige una hora de fin posterior al inicio y evita horarios superpuestos.'); return; }
    update('slots', { ...values, id: uid(), coordinador: userId }); setModal(false); setError('');
  }
  function book(e) {
    e.preventDefault();
    if (!available.some(s => s.id === selected)) { setError('Selecciona un horario disponible.'); return; }
    setData(previous => {
      if (previous.appointments.some(a => a.slot === selected && a.estatus === 'Confirmada')) return previous;
      return { ...previous, appointments: [...previous.appointments, { id: uid(), slot: selected, user: userId, estatus: 'Confirmada' }] };
    }); setSelected(''); setError(''); setTab('agenda'); notify('Tutoría agendada en la demostración.');
  }
  const shown = appointments.filter(a => { const slot = data.slots.find(s => s.id === a.slot); return tab === 'historial' ? a.estatus !== 'Confirmada' || slot?.fecha < today() : a.estatus === 'Confirmada' && slot?.fecha >= today(); });
  return <><Heading eyebrow={admin ? 'COORDINACIÓN / TUTORÍAS' : 'EMPRENDEDOR / TUTORÍAS'} title="Un espacio para avanzar juntos" description="Organiza las sesiones de acompañamiento de tu proyecto." /><div className="tabs">{(admin ? [['agenda', 'Agenda'], ['disponibilidad', 'Disponibilidad'], ['historial', 'Historial']] : [['agendar', 'Agendar'], ['agenda', 'Mis tutorías'], ['historial', 'Historial']]).map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</div>
    {tab === 'disponibilidad' ? <Panel><div className="row between"><h2>Mi disponibilidad</h2><button className="button" onClick={() => setModal(true)}>+ Agregar bloque</button></div><Table headings={['Día', 'Hora inicio', 'Hora fin', 'Estado', 'Acción']} empty={!data.slots.length}>{data.slots.map(s => { const booked = data.appointments.some(a => a.slot === s.id && a.estatus === 'Confirmada'); return <tr key={s.id}><td>{dateLabel(s.fecha)}</td><td>{s.inicio}</td><td>{s.fin}</td><td><Badge>{booked ? 'Reservado' : 'Disponible'}</Badge></td><td><button className="text-button danger" disabled={data.appointments.some(a => a.slot === s.id)} onClick={() => remove('slots', s.id)}>Eliminar</button></td></tr>; })}</Table></Panel> : tab === 'agendar' ? <Panel title="Agendar tutoría"><p className="muted">Coordinadora: Ana Martínez · Selecciona un horario disponible.</p><form onSubmit={book}><div className="slot-grid">{available.map(s => <label key={s.id} className={`slot ${selected === s.id ? 'selected' : ''}`}><input type="radio" name="slot" value={s.id} checked={selected === s.id} onChange={() => setSelected(s.id)} required /><strong>{dateLabel(s.fecha)}</strong><span>{s.inicio} – {s.fin}</span></label>)}</div>{!available.length && <Empty>No hay horarios disponibles por ahora.</Empty>}{error && <p className="error" role="alert">{error}</p>}<button className="button" disabled={!available.length}>Confirmar tutoría</button></form></Panel> : <Panel title={tab === 'historial' ? 'Historial de tutorías' : 'Próximas sesiones'}><Table headings={['Fecha', 'Horario', admin ? 'Emprendedor' : 'Coordinador', 'Estado', 'Acción']} empty={!shown.length}>{shown.map(a => { const s = data.slots.find(s => s.id === a.slot); return <tr key={a.id}><td>{dateLabel(s?.fecha)}</td><td>{s?.inicio} – {s?.fin}</td><td>{admin ? data.users.find(u => u.id === a.user)?.nombre : 'Ana Martínez'}</td><td><Badge>{a.estatus}</Badge></td><td>{a.estatus === 'Confirmada' && <div className="row">{admin && <button className="text-button" onClick={() => update('appointments', { ...a, estatus: 'Completado' })}>Completar</button>}<button className="text-button danger" onClick={() => { update('appointments', { ...a, estatus: 'Cancelada' }); notify('Tutoría cancelada en la demostración.'); }}>Cancelar</button></div>}</td></tr>; })}</Table></Panel>}
    {modal && <Modal title="Agregar disponibilidad" onClose={() => setModal(false)}><form className="form-stack" onSubmit={createSlot}><Field label="Fecha" name="fecha" type="date" min={today()} required /><div className="form-grid"><Field label="Hora inicio" name="inicio" type="time" required /><Field label="Hora fin" name="fin" type="time" required /></div>{error && <p className="error" role="alert">{error}</p>}<button className="button">Agregar bloque</button></form></Modal>}
  </>;
}
