"""Crear tablas usuarios y proyectos

Revision ID: 8881ea422f6a
Revises: 
Create Date: 2026-09-15 18:14:49.903419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8881ea422f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###